version: '3'

services:
  fastapi:
    command: uvicorn src.api:app --host 0.0.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    image: url_shortener 
    container_name: url_shortener_fastapi
    ports:
      - "8000:8000"